---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log4j-demo
spec:
  selector:
    matchLabels:
      app: log4j-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: log4j-demo
    spec:
      containers:
      - name: log4j-demo
        image: ghcr.io/christophetd/log4shell-vulnerable-app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: log4j-svc
  labels:
    app: log4j-svc
spec:
  ports:
  - port: 80
    name: log4j-port
    targetPort: 8080
    protocol: TCP
  selector:
    app: log4j-demo
  type: LoadBalancer
